### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by justjake** [rat9615/passport-notion#1]
The requests that this library make assume that the entire JSON response is returned in the first `data` callback here:

- https://github.com/rat9615/passport-notion/blob/c5011ec115081e04d395743366dfdcef87eb6ef8/lib/passport-notion/strategy.js#L113-L114

- (getUserProfile) https://github.com/rat9615/passport-notion/blob/c5011ec115081e04d395743366dfdcef87eb6ef8/lib/passport-notion/strategy.js#L143-L145

The solution is to wait for the `done` event on the response to parse the JSON. Example:

```typescript
    return new Promise((resolve, reject) => {
      const accessTokenRequest = https.request(requestOptions, (res) => {
        let data = ""
        res.on("data", (d) => {
          data += d
        })

        res.on("end", () => {
          try {
            resolve(JSON.parse(data))
          } catch (error) {
            reject(error)
          }
        })
      })

      accessTokenRequest.on("error", reject)
      accessTokenRequest.write(JSON.stringify(accessTokenBody))
      accessTokenRequest.end()
    })
  }
```

**Comment by rat9615** [comment]
If you're willing to raise a PR. I'll be glad to review and accept it.
